import type { NextPage } from 'next';
import Head from 'next/head';
import { Body404 } from '../components/Body404';
const Notfound: NextPage = () => {
  return (
    <div>
      <Head>
        <title>404</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body404 />
    </div>
  );
};
export default Notfound;
