import type { NextPage } from 'next';
import Head from 'next/head';

const Notfound: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Animes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
    </div>
  );
};
export default Notfound;
