import type { NextPage } from "next";
import Head from "next/head";
import { BodyInit } from "../components/BodyInit";
import { Header } from "../components/Header";
import { News } from "../components/News";

import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <BodyInit/>
      <News/>
    </div>
  );
};

export default Home;
