import type { NextPage } from 'next';
import Head from 'next/head';
import { BodyComponent } from '../components/Body';
import { BodyInit } from '../components/BodyInit';
import { News } from '../components/News';
import { RecentNews } from '../components/RecentNews';
import styles from '../styles/Home.module.css';
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodyInit />
      <News />
      <BodyComponent />
      <RecentNews />
    </div>
  );
};
export default Home;
